# Generated by Django 6.0.5 on 2026-05-13 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='plate_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
